### PR TITLE
Add anchor links to headers

### PR DESCRIPTION
**Pull request by Kobzol**
This allows linking to specific sections (headers) within a lesson page. I often want to send some specific part of the page to someone, but before I could only send a link to the whole page.
anchor

### CODE REVIEW

**Comment by frenzymadness** [comment]
I like the idea very much and also the implementation looks reasonable and readable. Tests are unhappy. I guess that this change has some impact on them because they might compare generated HTML with some templates. Could you please check it?

**Comment by encukou** [comment]
I don't like generating link IDs automatically, because they break when you reword the header.

**Comment by Kobzol** [comment]
That makes sense, although I don't think that this situation occurs frequently, and I want this functionality for providing more accurate links (that I immediately send to someone), more than providing true **perma**links.

An alternative could be indexing the headers from `0` to `n`, that would survive header change name, but it would break on header reorganization (removal, insertion, move).

Or we could somehow attach fixed IDs to headers in Markdown, but that seems cumbersome and it would need a change in all existing materials. And it would also not prevent IDs disappearing when a header is removed.

**Comment by encukou** [comment]
Right, numbering would be even worse: old links would point to *unrelated* sections rather than the whole page.
Don't let me block this PR. A better way can be added in the future.


Please run tests locally with `TEST_NAUCSE_DUMP_YAML=1`, and commit the result. Then we can check the changes to the HTML.

**Comment by Kobzol** [comment]
I blessed the tests.

**Comment by encukou** [comment]
I did two more changes:
    - Change the class name the (IDs aren't necessarily permanent)
    - Add prefix to generated IDs, so they won't clash with non-content IDs

**Comment by encukou** [comment]
Thanks for the PR!

**Pull request merged**
